- src/hot.ts
When loading each package:
* Accept all package changes
* Subscribe to onDispose --> when HMR unloads this package, we remove the relevant shells from repluggable
* If we loaded this module during apply phase, this means we are during HMR for it, so add the shells to repluggable
> making hmr great again

- README.md
Readme of creating new project is not up to date
* Global create-react-app not supported as global command -> changed to run with `npx`
* Conflicting react versions -> Forced React@16.14 until React@17 is tested
Fixing https://github.com/wix/repluggable/issues/147
> Fix create-new-project section in README

- src/throttledStore.tsx
Fix a bug in which observable notifications were missed (because of another dispatch)
> Don't clear pendingObservableNotifications on dispatch

- src/API.ts
- src/appHost.tsx
- src/connectWithShell.tsx
- src/renderSlotComponents.tsx
- test/connectWithShell.spec.tsx
- testKit/index.tsx
Add `renderOutsideProvider` option to `connectWithShell` function, that wraps the the connected component with host and shell contexts .
This should allow valid connection of components to the store, even when they're not rendered inside the main view.
> Add renderOutsideProvider option to connectWithShell

- src/IterableWeakMap.ts
- src/appHost.tsx
- test/IterableWeakMap.spec.ts
- test/appHost.spec.ts
Today anytime when memoizeForState is used, it creates a memoized function that is live forever in memory.
This PR introduce WeakMap storage for memoized function(instead of array), they will be cleared whenever memoized function will be GC.
IterableWeakMap example is taken from https://github.com/tc39/proposal-weakrefs#iterable-weakmaps
Note: IterableWeakMap uses [FinalizationRegistry](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry#browser_compatibility) and [WeakRef](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakRef#browser_compatibility) that **are not** supported by all browsers.
> Memory leak fix in memoizeForState

- src/throttledStore.tsx
Call `notifyObservers` before we call `notifySubscribers`, so when `notifySubscribers` is called we would already have the updated observers.
> Notify observers before the subscribers on state update

- src/appHost.tsx
- test/appHost.spec.ts
Flush memoized functions when observable is updated
> Flush memoized functions on observer update

- src/connectWithShell.tsx
- test/connectWithShell.spec.tsx
Refactor `observeWithShell` to work with pure components, and add some tests
> observeWithShell for pure component

- src/connectWithShell.tsx
Using `connectWithShellAndObserve` would constantly raise `attempt to create component type outside of Entry Point lifecycle` error as the connectWithShell factory was called inside the observing component wrapper constructor.
> Fix entry point lifecycle error in connectWithShellAndObserve

- src/connectWithShell.tsx
- test/connectWithShell.spec.tsx
Add `mapShellToStaticProps` function to `observeWithShell`, so we'll be able to add props to the component.
These are StaticProps - they won't be updated as the component is not connected.
> Add mapShellToStaticProps to observeWithShell

- src/API.ts
- src/appHost.tsx
- src/connectWithShell.tsx
- src/throttledStore.tsx
- test/connectWithShell.spec.tsx
- testKit/withThrowOnError.ts
Throw an error when calling observable's `current` function inside notifySubscribers flow, as it means the user is reading an observable inside a store subscription. Instead the observable should be read in observing flow.
> Prevent reading observables inside notifySubscribers

- src/throttledStore.tsx
Remove the call to `resetPendingBroadcastNotifications` in `dispatch` call.
All pending notifications (of both observers and subscribers) are cleared on each `notify` call. There's no point clearing subscribers notifications on each `dispatch`.
This caused the following bug: 
Two dispatch calls were made. 
The first one changed the 'subscribers state' and turned the `pendingBroadcastNotification`. 
The second call was made right after it. First thing in the dispatch flow was turning off `pendingBroadcastNotification`, and then we found out the second dispatch changed on 'observers state' and therefore the `pendingObservableNotifications` was updated.
Right after that, we got an animation frame and `notifyAll` was called, but only `pendingObservableNotifications` was on, and so we didn't …
> Don't clear subscribers on dispatch

- src/connectWithShell.tsx
In order to prevent foul usage of `allowOutOfEntrypoint`
> Add documentation to connectWithShell

- src/appHost.tsx
- src/throttledStore.tsx
- test/appHost.spec.ts
This PR fixes the issue with cached function(with memoizeForState):
When action is dispatched from sync code (for example inside React Component `didMount` hook, or inside `store.subscribe`), memoized function doesn't clear cache and return cached(outdated) value.
With fixes, when action is dispatched from sync code, it's clear cache(before execution goes out from execution stack) which is guarantee that memoized function will return latest data.
For example:
```
// sync code start
dispatch({type: 'ACTION'})
someAPI.memMethod() // this will return latest value
// sync code end
```
> Fix cache flushing on store change

- src/connectWithShell.tsx
- test/connectWithShell.spec.tsx
Attempt to make shouldComponentUpdate connect option compatible with redux connect(areOwnPropsEqual, etc.).
By exposing ownProps/stateProps to shouldComponentUpdate connect options.
Why?
The result of shouldComponentUpdate mainly controlled by API from shell and it's not possible to do via props, so I can't control optimisation per component instance.
Example:
In this example, AuthorizationTooltip children is not rendered if `isPerformingAction()` returns true.
In some cases I want children to be rendered, but I can't control it per component instance, only globally.
```
export function createAuthorizationTooltip(boundShell: Shell) {
return connectWithShell<
{},
AuthorizationTooltipProps,
AuthorizationTooltipStateProps
>(mapStateToProps, undefined, boundShell, {
shouldComponentUpdate: …
```
> Extend connect shouldComponentUpdate option with additional argument

- src/API.ts
- src/appHost.tsx
- src/extensionSlot.ts
- test/appHost.spec.ts
- test/extensionSlot.spec.ts
Performance measurements
---
Steps: 
1. Add the code below in `createAppHost`
initialize a flag to indicate if installing shells
accumulate execution duration of executeInstallShell just before the return statement
2. Run repluggable locally 
3. Run studio with local repluggable - Add `&debug=true` to url params + use directly or any other extension to redirect the request for repluggable to the local host
4. Refresh to load the editor
5. Open dev tools and run `window.total`
**Note** that I also disabled shell logger for these specific measurements.
Master branch
Current branch
> EDIX-20625 call slot subscribers when host resumes shells installation

- src/API.ts
- src/appHost.tsx
- src/throttledStore.tsx
- test/connectWithShell.spec.tsx
- testKit/index.tsx
- Add `deferSubscriberNotifications` Function that defers subscribers (and observables) notification until the end of some action. This is necessary when running a flow that creates intermediate states we don't want to react to. 
- To handle the conflict between `deferSubscriberNotifications` and `flush`, add optional config to the flush function:
- `excecutionType: scheduled`- meaning flush would happen right after we stop deferring notifications
- `excecutionType: immediate` - meaning flush would happen immediately regardless if notifications are currently being deferred.
In general, the `deferSubscriberNotifications` solution is:
- `deferSubscriberNotifications` receives some action we would like to perform while deferring notifications.
- If notifications are already deferred, run …
> Defer notifications while performing action

- src/throttledStore.tsx
- test/connectWithShell.spec.tsx
This PR fixes a bug with `deferSubscriberNotifications`, where it's called right after a state update. 
In general, when dispatching a state update, we update `pendingBroadcastNotification` and notify all on the next animation frame. 
When calling `deferSubscriberNotifications` right after a dispatch, we face with a case where we should have notified subscribers, but there was no animation frame yet, and so we start deferring notification before notifying on the previous state update. Meaning, we do not notify about the state update that happened right before we started deferring until we stop deferring all notifications.
This is an unexpected behaviour, and to solve this, this PR adds executes all pending actions before starting to defer notifications, in case there are pending …
> Notify if needed before deferring subscriber notifications

- src/connectWithShell.tsx
- test/connectWithShell.spec.tsx
In Redux, the calculation of the `mergedProps` depends on determining whether `ownProps` have changed. If `ownProps` change while `shouldComponentUpdate` is blocking the recalculation of `mergedProps`, a subsequent state update or propagation of seemingly unchanged `ownProps` (which appear the same as the last `ownProps` but differ from the `ownProps` before the blocking period) may result in incorrect `mergedProps` calculation. This issue arises because changes in `ownProps` during the blocking period are not taken into account.
This PR introduces a mechanism to detect changes in `ownProps` that occur while `shouldComponentUpdate` optimization is in effect. If such changes are detected during this blocking period, the next permitted component update will trigger a recalculation of …
> arePropsEqualFuncWrapper

- src/API.ts
- src/appHost.tsx
- test/appHost.spec.ts
- testKit/index.tsx
Add @DanielKag's amazing `lazy` logic, that given a function creates an object with a lazy-evaluated getter for that function (calculated only once).
> Add shell.lazyEvaluator

- src/interceptAnyObject.ts
- src/monitorAPI.ts
- test/interceptAnyObject.spec.ts
shell.getAPI returns empty objects for several APIs even though real implementation was contributed.
When the repluggable host is created with the `disableMonitoring` option off, `monitorAPI` is used to intercept and monitor any function in the API. This is done by contributing an intercepted API object instead of the contributed API. The intercepted API object is created using `interceptAnyObject`, that recursively intercepts all functions in the nested object and wraps them with monitoring logic. 
The problem is that `interceptAnyObject` assumes the API is a plain object, as can be seen by its type. When passed an API that is not a plain object (e.g. a function), `_.mapValues` returns an empty object and the API implementation is lost.
**The assumption that API is a plain object is …
> Bug fix: interceptAnyObject used in monitorAPI

- src/appHost.tsx
- src/throttledStore.tsx
- test/connectWithShell.spec.tsx
In this PR, I added an option to clear `memoizeForState` cache on every state change, if deferring notifications.
This is done because we normally clear the memoizeForState` cache only when notifying subscribers, which does not happen while deferring notifications. This may cause incorrect results.
Currently this is done only when given an optional argument to `deferSubscriberNotifications` (which makes the code temporarily ugly), so we can verify that it does not cause performance issues. In the future we would like to do it by default.
> Clear memoized for state while deferirng notifications

- src/repluggableAppDebug/debug.d.ts
- src/repluggableAppDebug/repluggableAppDebug.ts
- test/repluggableAppDebug.spec.ts
problem: when there is an issue with an API/Entrypoint, sometimes you get way too many unready entry points, which most depend on one or more APIs.
in this  PR we add a new method to repluggableAppDebug that returns an array of APIs that are not ready, when the first item in the array is the API that caused all the other APIs/Entry points to be not ready.
> add function to repluggable app debug

- src/throttledStore.tsx
Removed caching of selector in case of using observable state, to avoid bugs of outdated values read from the observable state.
> Observable State: remove cached selector.

- .github/workflows/master.yml
- .github/workflows/pr.yml
- .github/workflows/release.yml
- .yarnrc
- .yarnrc.yml
- package.json
- packages/repluggable-core/package.json
This PR goal is to adjust the Github Actions workflows for the new monorepo setup.
`repluggable-core` and `repluggable` versions should be synced and coupled for each release.
So in every publish flow (deploy preview or release) we set `repluggable`'s dependency to `repluggable-core@current-version`
We use `yarn workspaces` power to run inner scripts from the root directory.
From the root directory, `build` and `test` run the correlate script in all packages in a topological order.
> Adjust `Github Actions` workflows to the new setup

- packages/repluggable-core/package.json
- packages/repluggable-core/src/API.ts
- yarn.lock
This pr is needed for the refactor.
In order to actually move the implementations we first copy the types.
This pr copy the types which are not connected to any concreate implementation and not staff which are need the implementation like the throttled store. 
The plan is 
1. copy the types
2. Move implementation
3. Use implementation in repluggable
4. Use type connected to that implementation from repluggable-core and not own copy
5. Repeat
Side note: 
I also though just about moving but as shell is used in every type and core can't use redux and need to remove functions from it, it means we will need to somehow have two versions of shell which would be very difficult before moving the implementation.
> Copy public API to repluggable-core

- packages/repluggable/src/throttledStore.tsx
This pr goal is to make the throttle store work also on server.
1. not use request animation frame and instead use setTimeout with 0, publish to the next frame.
2. Change the names which will be more server compatibly in the spirt of observer pattern with a publisher.
> Make ThrottledStore server compatible

- packages/repluggable/src/appHost.tsx
- packages/repluggable/src/throttledStore.tsx
This pr is just a pr to remove the variables I forgot to remove in the last pr of throttled store.
https://github.com/wix-incubator/repluggable/commit/ac03fce318c5044f79fb946470e7a17b0748bb3e
> Remove unused variables from input for throttled store

- packages/repluggable/src/API.ts
- packages/repluggable/src/appHost.ts
- packages/repluggable/src/connectWithShell.tsx
- packages/repluggable/testKit/index.tsx
This pr is part of the effort to make repluggable server compatible. 
I remove React from app host by deleting the only function which uses react wrapWithShellRenderer.
to do that I add into the privateShell one function to get the Host.
Its ok as it only in the private shell which is used only inside repluggable. 
then using the host connectWithShell create his own wrapWithShellRenderer so only when needed we use React.
for now the appHost is exposed via TEMP_getAppHost in the future will will replace the access only via privateSymbol of repluggable
> Remove shell renderer from host

- packages/repluggable/src/API.ts
- packages/repluggable/src/appHost.ts
- packages/repluggable/src/connectWithShell.tsx
- packages/repluggable/src/throttledStore.tsx
- packages/repluggable/test/appHost.spec.ts
- packages/repluggable/testKit/index.tsx
- packages/repluggable/testKit/mockPackage.ts
Implement `hasAPI` and `hasSlot` functions, to allow checking if some API\Slot exist on the host\shell.
Note that same as `getAPI` and `getSlot`, the implementation is slightly different between the host and the shell.
> Implement hasAPI  & hasSlot

- packages/repluggable/src/throttledStore.ts
In my last refactor of throttled store I introduced a very nice bug.
this is the pr: https://github.com/wix-incubator/repluggable/pull/280.
the bug happened because before the change the check was using:
`!requestId` i wanted to be more explicit and used `id === null`
but if you put null and don't refernce the id anymore its garbage collected and become undefined which means that we will not invoke any subscribers int he future.  
this pr fixes it by using `undefined` for the default value for the id.
we can think on adding test in feature prs but we want to unblock bump of repluggable as fast as possible
> Fix throttled store bug

- packages/repluggable/src/API.ts
This change copy the type of SlotKey back into 'repluggable' so the forbidden export test should pass.
Why the test fail?
If you are making a re-export for some reason that complicated test fails, so in order to unblock other repos to update repluggable I copy it back in until I will properly move everything into repluggable core without breaking that test.
> Fix forbidden export test

- packages/repluggable-core/src/API.ts
- packages/repluggable/src/API.ts
- packages/repluggable/src/appHost.ts
- packages/repluggable/test/appHost.spec.ts
Add `onDeclarationsChanged` API, to register callbacks that will be called when a host declaration has changed. This includes declaring a slot or contributing an API. 
To avoid an overhead, `onDeclarationsChanged` callbacks are batch-executed. This means that for an entry point attach \ extend phase, `onDeclarationsChanged` will be called only once for all new declarations in that phase. Same for removing declarations in the entry point detach phase.
> On declarations changed

- packages/repluggable/testKit/package.json
the package json inside the testkit creates a type problem because the types are taken from the dist.
to overcome this problem we remove the package.json in the testkit folder, it is not needed as the package.json file in the repluggable package (not in the root) has files: "*", which basically exports everything including the testkit.
> remove testkit package json as the repluggable package JSON exports all

- packages/repluggable/testKit/package.json
Reverts wix-incubator/repluggable#299
This pr breaks REP:
as it tries to bring the code from src and not from dist
> Revert "remove testkit package json as the repluggable package JSON exports all"

- packages/repluggable/src/index.ts
- packages/repluggable/src/lazyCreateConnectedComponent.ts
- packages/repluggable/test/lazyCreateConnectedComponent.spec.tsx
**TL;DR**
Like [React.lazy](https://react.dev/reference/react/lazy) but for components created with [repluggable `createConnected` function](https://github.com/wix-incubator/repluggable?tab=readme-ov-file#creating-react-components).
**Goal**: 
- load initial screen for user as fast as possible
- allow to load components dynamically instead of bundling them to the main chunk, **therefore load initial screen for user faster** 
```ts
import { lazyCreateConnectedComponent } from 'repluggable';
const MyHeavyPanelLazy = lazyCreateConnectedComponent(shell,
() => import('./MyHeavyPanel.tsx')
);
panelAPI.contributePanel({
component: () => (
<Suspense fallback="loading..">
<MyHeavyPanelLazy />
</Suspense>
),
});
```
where `./MyHeavyPanel.tsx` is module witch has:
```ts
// default export
export …
```
> add `lazyCreateConnectedComponent` (Like `React.lazy` but for repluggable)

- packages/repluggable-core/debug/index.ts
- packages/repluggable-core/package.json
- packages/repluggable-core/tsconfig.debug.json
- packages/repluggable/debug/index.ts
- packages/repluggable/package.json
- packages/repluggable/tsconfig.debug.json
This PR introduces the ability to import the `repluggableAppDebugInfo` type and extends the `window` declaration accordingly.
```ts
import 'repluggable/debug'
// or: import 'repluggable-core/debug'
const apis = window.repluggableAppDebug.utils.apis;
```
You can also import the actual types:
```
import { RepluggableAppDebugInfo, APIDebugInfo} from 'repluggable/debug'
```
> **Note:** Importing from `'repluggable'` will not pollute the global object.
> Export `repluggable/debug`

- packages/repluggable-core/src/repluggableAppDebug/debug.d.ts
- packages/repluggable-core/src/repluggableAppDebug/repluggableAppDebug.ts
- packages/repluggable-core/test/repluggableAppDebug.spec.ts
the implementation of getRootUnreadyAPI had an issue, it returned an array, we now fix it to return a single API
> return a single API instead of an array
